# These are supported funding model platforms

# github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
# ko_fi: # Replace with a single Ko-fi username
# liberapay: # Replace with a single Liberapay username
custom: ["https://paypal.me/AlejandroA36?country.x=AR&locale.x=es_XC"]
